### ISSUE TITLE
使用\think\facade\Log::error('代志大条了');时报错

### ISSUE THREAD

**Issue by fkueyu** [hbh112233abc/ding-bot#1]
这样用：
\think\facade\Log::error('代志大条了');
$ding = new \bingher\ding\DingBot;
$ding->text('测试信息');

[2] ErrorException in DingBot.php line 40
array_merge(): Expected parameter 1 to be an array, bool given

**Comment by hbh112233abc** [comment]
你的thinkphp是什么版本的呢?

**Comment by fkueyu** [comment]
thinkphp6 rc4(报错的时候好像还是rc3），php 7.3.7

**Comment by hbh112233abc** [comment]
有没有qq 方便看一下你的配置么?

**Comment by fkueyu** [comment]
78481944

**Comment by hbh112233abc** [comment]
搞定 谢谢
